# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5332ab3cf4d0414c30ea33cfafec93676ee7d5ce1098611e11618f6bf4f66e2ef22ced5ef37accf297a3f32590548ef74d2c656673a0b32a4a3d6b9e400d80e

test:
  secret_key_base: 2ee8dbdcd984d9fdb76ff556be97f04a9cb9dde8d51106fd26fe1d3ddb6bebfd06335c9b5e8d7dab547d0b9c1062979cc4b5ae924734c05790e86b0f76802ec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
